version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: pharma-backend-prod
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: pharma-db-prod
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env.production
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data:
